---
namespace: robertdebock
name: system
version: 1.0.2
readme: README.md
authors:
  - "Robert de Bock (@robertdebock)"
description: Ansible module for process management
license:
  - Apache-2.0
tags:
  - process
  - system
  - management
  - linux
repository: https://github.com/robertdebock/ansible-collection-system
documentation: https://github.com/robertdebock/ansible-collection-system
homepage: https://github.com/robertdebock/ansible-collection-system
issues: https://github.com/robertdebock/ansible-collection-system/issues 
