---
name: Publish to Ansible Galaxy

on:
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install Ansible
        run: |
          pip install ansible-core

      - name: Build collection
        run: |
          ansible-galaxy collection build ansible_collections/robertdebock/system --output-path .

      - name: Publish to Galaxy
        run: |
          echo "Publishing collection to Galaxy"
          ansible-galaxy collection publish robertdebock-system-*.tar.gz --token ${{ secrets.GALAXY_API_KEY }}
